{"name": "Negative test: Patch object with invalid data", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status: 405\nassert 405 in [400, 404, 422]\n +  where 405 = <Response [405]>.status_code", "trace": "token = 'rkC1mNuXZ646pOl', patch_data = {'id': 123456789}\n\n    @allure.title(\"Negative test: Patch object with invalid data\")\n    @pytest.mark.parametrize(\"patch_data\", invalid_patch_payloads)\n    def test_patch_object_negative(token, patch_data):\n        obj_patch = ObjectPatch()\n        obj_patch.set_token(token)\n    \n        object_id = 999999  # use nonexistent ID for safety\n    \n        with allure.step(\"Try to PATCH object with invalid data\"):\n            response = obj_patch.patch_object(object_id, patch_data)\n>           assert response.status_code in [400, 404, 422], f\"Unexpected status: {response.status_code}\"\nE           AssertionError: Unexpected status: 405\nE           assert 405 in [400, 404, 422]\nE            +  where 405 = <Response [405]>.status_code\n\ntests\\test_patch_object_negative.py:18: AssertionError"}, "steps": [{"name": "Try to PATCH object with invalid data", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected status: 405\nassert 405 in [400, 404, 422]\n +  where 405 = <Response [405]>.status_code\n", "trace": "  File \"C:\\Users\\Sergey\\Projects\\api-automation-framework\\tests\\test_patch_object_negative.py\", line 18, in test_patch_object_negative\n    assert response.status_code in [400, 404, 422], f\"Unexpected status: {response.status_code}\"\n"}, "start": 1748318522284, "stop": 1748318522594}], "parameters": [{"name": "patch_data", "value": "{'id': 123456789}"}], "start": 1748318522284, "stop": 1748318522594, "uuid": "5092320b-8293-4161-a4c2-80cd20530ed7", "historyId": "ccf36ce2ac5044dd7347b381cf7e9e2b", "testCaseId": "70f805e9fced0522ce229ca93232757c", "fullName": "tests.test_patch_object_negative#test_patch_object_negative", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_patch_object_negative"}, {"name": "host", "value": "Sergo"}, {"name": "thread", "value": "25544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_patch_object_negative"}]}